#cloud-config
coreos:
    etcd:
        name: {{{name}}}
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
        discovery: {{{discoveryToken}}}
        addr: $private_ipv4:4001
        peer-addr: $private_ipv4:7001
    fleet:
        public-ip: $private_ipv4
        metadata: region=us-east
    units:
      - name: etcd.service
        command: start
      - name: fleet.service
        command: start
        after: etcd.service
ssh_authorized_keys:
  - {{{sshAuthorizedKey}}}
hostname: {{{hostname}}}